-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 16:50:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_usuarios
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_usuarios` ;

-- -----------------------------------------------------
-- Schema db_usuarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_usuarios` DEFAULT CHARACTER SET utf8 ;
USE `db_usuarios` ;

-- -----------------------------------------------------
-- Table `db_usuarios`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_usuarios`.`usuario` ;

CREATE TABLE IF NOT EXISTS `db_usuarios`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_usuarios`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_usuarios`;
INSERT INTO `db_usuarios`.`usuario` (`id`, `email`, `password`, `nombre`, `age`) VALUES (DEFAULT, 'a@a.a', '1234', 'Aaaa Aaaa', 22);

COMMIT;

